sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "T6kczVai2UURy3T+2qJzS7vQRGHpkZIt3L6iHdiCL/IRTK0wi5Wz3d/1atMyVh4Azg+TIGy2N6mKLiYHkUGmOYA1nUJ1o5WhYVb3AgwM08MTAsEYfho3+6LUBPv1sSKnsITYTU0UEBRaoybHcIzaqaW+aN0FMpo7EwDI3YmuOy7e54QPChDxB5fh5bWzusV0UkAM7MFvkbmSdWS6MsETWwb+hr6LUrPPNaRFlSf95+NbfBuN4XuQYifCaHZaOYXxdcEQ+EaytrBzZsDUOiE74IdeT/37dtfQjavK7HdWrv9o+d+hrPwozuhuHMWmxwFUKg/xp6iDknrMko2y+DVSbecfdJJaGCzmA+JVptSMZQhx/ZBY4A4SmfYcZFKxF6KyJr6iNb1zoqmtbZDyiK3dkmt9kO1ZNah61YVsfi/EbY1V2mdwvRHVK8sQWiaunK3/DdhgeVJ6GzlJjnq7HTNTHuDV3B/LuTbJdnQxD2pjlWwG2/VarNEfI6BLx7XvdzhPlAuPOCw+n6pWQ6PER2L8xzRrfleEi7Gqc/PiGYQd56RXHqWthH5VabSznz6gKYVubN2SPpUc1h6VgH/vAPoBDh+VKjyT7G9mpIn+uFPSrTjUpbFpKmivopdqkzuh7kuiBjOBopEfWxva3uyQaxGMAm4W3vCZ46jiRnbGPyYSjXQ="
branches:
  only:
    - master
